### ISSUE TITLE
run example for  openresty 

### ISSUE THREAD

**Issue by HappySky2046** [iresty/lua-resty-radixtree#3]
env: 
os: CentOS Linux release 7.6.1810 (Core)
nginx version: openresty/1.15.8.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled

nginx.conf :

location / {
            root   html;
            index  index.html index.htm;
            content_by_lua_block {
                local radix = require("resty.radixtree")
                local rx = radix.new({
                    {
                        path = "/aa",
                        metadata = "metadata /aa",
                        host = "foo.com",
                        method = {"GET", "POST"},
                        remote_addr = "0.0.0.0",
                    },
                    {
                        path = "/bb*",
                        metadata = "metadata /bb",
                        host = {"*.bar.com", "gloo.com"},
                        method = {"GET", "POST", "PUT"},
                        remote_addr = "fe80:fe80::/64",
                    }
                })

                ngx.say(rx:match("/aa", {host = ngx.var.host,
                                         method = ngx.req.get_method,
                                         remote_addr = ngx.var.remote_addr}))
            }
        }

error.log 
radixtree.lua:338: bad argument #2 to 'band' (number expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'band'
lualib/resty/radixtree.lua:338: in function 'match_route_opts'
lualib/resty/radixtree.lua:414: in function 'match_route'
lualib/resty/radixtree.lua:474: in function 'match'

test:
curl   127.0.0.1/aa

**Comment by membphis** [comment]
`method = ngx.req.get_method` -> `method = ngx.req.get_method()`

**Comment by membphis** [comment]
and I added more check to crash: https://github.com/iresty/lua-resty-radixtree/commit/78dd8bc070f87b3590bc6bc6940fcdec9905a49e
